const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let cart=JSON.parse(localStorage.getItem('jecheol_cart')||'[]'); let activeMarket='photo'; let selectedPhotoCandidate='사진으로 확인한 재료';
const catalog={'8801234567890':['양파 1kg',3500],'8800000000001':['배추 1포기',4800],'8800000000002':['애호박 1개',1800],'8800000000003':['돼지고기 앞다리살 600g',8900],'8800000000004':['고등어 2마리',6500],'8800000000005':['오징어 2마리',7900]};
['돼지고기 앞다리살 600g','소고기 국거리 300g','닭고기 1마리','고등어 2마리','오징어 2마리','새우 300g'].forEach(x=>$('#manualItem')?.append(new Option(x,x)));
function save(){localStorage.setItem('jecheol_cart',JSON.stringify(cart));renderCart()}
function go(id){$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));window.scrollTo({top:0,behavior:'smooth'});if(id==='instructor')renderInstructor()}
$$('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));
function renderCart(){let total=cart.reduce((s,x)=>s+x.price*x.qty,0);$('#cartBadge').textContent=cart.length;$('#cartTotal').textContent=total.toLocaleString()+'원';$('#cartItems').innerHTML=cart.length?cart.map((x,i)=>`<div class="cart-row card"><div><b>${x.name}</b><small>${x.price.toLocaleString()}원 · ${x.source||'직접입력'}</small></div><div><button class="secondary" data-minus="${i}">−</button> ${x.qty} <button class="secondary" data-plus="${i}">＋</button></div></div>`).join(''):'<div class="card hint">아직 담긴 재료가 없어요. 시장 방문 모드에서 재료를 담아보세요.</div>';$$('[data-minus]').forEach(b=>b.onclick=()=>{cart[+b.dataset.minus].qty--;if(cart[+b.dataset.minus].qty<1)cart.splice(+b.dataset.minus,1);save()});$$('[data-plus]').forEach(b=>b.onclick=()=>{cart[+b.dataset.plus].qty++;save()})}
renderCart();
async function loadLivePrices(){const base=window.APP_CONFIG?.API_BASE_URL;if(!base||base.includes('127.0.0.1'))return;const home=$('#home');const card=document.createElement('div');card.className='live-price card';card.innerHTML='<b>오늘의 KAMIS 시세</b><p class="hint">최신 가격을 불러오는 중입니다.</p>';home.append(card);try{const rs=await Promise.all(['채소류','축산물','수산물'].map(c=>fetch(`${base}/api/market/current?category=${encodeURIComponent(c)}&limit=4`).then(r=>r.json())));const items=rs.flatMap(x=>x.items||[]);card.innerHTML='<div class="live-head"><b>오늘의 KAMIS 시세</b><small>서버 연동값</small></div>'+(items.length?items.map(x=>`<div class="price-line"><span>${x.name}<small>${x.unit||''}</small></span><strong>${x.price}원</strong></div>`).join(''):'<p class="hint">현재 시세를 불러오지 못했습니다. 직접 가격을 입력할 수 있습니다.</p>')}catch(e){card.innerHTML='<b>오늘의 KAMIS 시세</b><p class="hint">시세 서버에 연결되지 않아 입력한 가격으로 계속할 수 있습니다.</p>'}}
loadLivePrices();
$$('[data-market]').forEach(b=>b.onclick=()=>{activeMarket=b.dataset.market;$$('[data-market]').forEach(x=>x.classList.toggle('selected',x===b));['Photo','Barcode','Manual'].forEach(x=>$('#market'+x).classList.toggle('hidden',x.toLowerCase()!==activeMarket))});
$('#photoInput').onchange=e=>{let f=e.target.files[0];if(!f)return;let img=$('#photoPreview');img.src=URL.createObjectURL(f);img.hidden=false;let words=['배추','무','양파','애호박','오이','시금치','사과','돼지','소고기','쇠고기','닭','고등어','생선','오징어','새우','갈치'];let hit=words.find(w=>f.name.includes(w))||'재료';let candidates=hit==='재료'?['채소 후보','육류 후보','수산물 후보']:[hit,hit==='돼지'?'소고기':'돼지고기',hit==='고등어'?'오징어':'새우'];selectedPhotoCandidate=candidates[0];$('#photoGuess').innerHTML=`사진 인식 후보를 확인해 주세요.<div class="candidates">${candidates.map((x,i)=>`<button class="candidate ${i===0?'selected':''}" data-candidate="${x}">${i+1}. ${x}</button>`).join('')}</div>`;$$('.candidate').forEach(b=>b.onclick=()=>{$$('.candidate').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');selectedPhotoCandidate=b.dataset.candidate})};
$('#barcodeInput').oninput=e=>{let x=catalog[e.target.value];$('#barcodeResult').textContent=x?`인식 결과: ${x[0]} · 예상 ${x[1].toLocaleString()}원`:'상품 정보를 찾지 못했어요. 직접 입력으로 이어갈 수 있습니다.'};
$('#scanBtn').onclick=async()=>{if(!('BarcodeDetector' in window)){ $('#barcodeResult').textContent='이 브라우저는 카메라 바코드 인식을 지원하지 않아 숫자 입력을 사용해 주세요.';return}$('#barcodeResult').textContent='카메라 권한을 허용하면 바코드를 비춰주세요. (실기기 연결 후 연동)'};
$('#addMarketBtn').onclick=()=>{let name,price,source;if(activeMarket==='manual'){name=$('#manualItem').value;price=+$('#manualPrice').value||0;source='직접입력'}else if(activeMarket==='barcode'){let x=catalog[$('#barcodeInput').value];name=x?.[0]||'바코드 상품';price=x?.[1]||0;source='바코드'}else{name=selectedPhotoCandidate;price=0;source='사진 후보'}if(!name||(!price&&source!=='사진 후보')){$('#marketMessage').textContent='재료와 가격을 확인해 주세요.';return}let old=cart.find(x=>x.name===name);old?old.qty++:cart.push({name,price,qty:1,source});save();$('#marketMessage').textContent=`${name}을(를) 장바구니에 담았어요.`;go('cart')};
$('#recommendBtn').onclick=()=>{let p=+$('#people').value||2;let foods=[['배추된장국','배추·두부·대파','따뜻하고 든든한 국물'],['제철 채소 비빔밥','시금치·당근·계란','냉장고 재료 활용'],['애호박 볶음 정식','애호박·양파·돼지고기','30분 안에 완성']];$('#recommendResult').innerHTML=foods.map((x,i)=>`<article class="recommend"><b>${i+1}. ${x[0]}</b><p>${x[1]}</p><small>${x[2]} · ${p}인 기준</small><br><button class="secondary add-food" data-i="${i}">재료 담기</button></article>`).join('');$$('.add-food').forEach(b=>b.onclick=()=>{let x=foods[+b.dataset.i];cart.push({name:x[0]+' 재료',price:12000,qty:1,source:'밥상추천'});save();go('cart')})};
function renderInstructor(){let total=cart.reduce((s,x)=>s+x.price*x.qty,0),n=+$('#classPeople').value||1;$('#perPerson').textContent=Math.ceil(total/n).toLocaleString()+'원';}$('#classPeople').oninput=renderInstructor;$('#copyClass').onclick=()=>{$('#classMessage').textContent='수업 장보기 목록이 준비됐어요. 장바구니의 목록 저장 버튼으로 공유할 수 있습니다.';renderInstructor()};$('#exportCart').onclick=()=>{let text=cart.map(x=>`${x.name} × ${x.qty}`).join('\n')||'장바구니가 비어 있습니다.';navigator.clipboard?.writeText(text);$('#cartItems').insertAdjacentHTML('afterend','<p class="message">장보기 목록을 클립보드에 복사했어요.</p>')};
